version: '3'
services:
  app:
    build:
      context: containers/rails
    container_name: rails-app-apiserver
    env_file:
      - ./containers/db/db.env
    #for development
    ports:
      - 3000:3000
    command:
      ## for development
      bundle exec rails s -b "0.0.0.0"
      ## for builde staging
      #bundle exec puma -C config/puma.rb
    volumes:
      - ./containers/rails/:/webapp
      - ./tmp-data:/webapp/tmp
      - ./log-data:/webapp/log
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: rails-app-db
    ports:
      - 5432:5432
    env_file:
      - ./containers/db/db.env
    volumes:
      - ./containers/db/data:/var/lib/postgresql/data
  web:
    build:
      context: containers/nginx
    container_name: rails-app-nginx
    volumes:
      - ./public-data/dist:/var/www/html
      - ./tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
  vue:
    build:
      context: ./containers/vue
    container_name: rails-app-vue
    command: npm run serve
    volumes:
      - ./public-data:/app
    tty: true
    ports:
      - 8000:8080
    depends_on: 
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: